// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jyaeitdvvfpwncwtvtgh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp5YWVpdGR2dmZwd25jd3R2dGdoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1ODYyNzEsImV4cCI6MjA3MDE2MjI3MX0.Zcy2yFbEteWiX4ptf9wSiW_8PfaxEYkofTkbCAlWtI4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});